### ISSUE TITLE
preserve not setted properties on update

### ISSUE THREAD

**Issue by bb-git** [mostachoio/MoABContactsManager#2]
It would be great, if properties that are not set when updating the contact would not change instead of beeing deleted.

**Comment by bb-git** [comment]
Still not working for me. The phones property is not set and nslog doesn't get called, but the phonenumbers of my contact disappears in my addressbook. notes are preserved, by the way.

```
    MoContact *moContact = [[MoContact alloc] init];
    [moContact setFirstName:contact.firstname];
    [moContact setLastName:contact.lastname];
        [moContact setContactId:contact.abid];
        NSLog(@"Saving Contact");
        if(moContact.phones && [moContact.phones count] > 0){
            NSLog(@"phones availabes and should save");
        }
        [[MoABContactsManager sharedManager] updateContact:moContact completion:^(NSError *error) {
            if (error) {

            }
        }];
```

**Comment by diegof29** [comment]
Are you fetching the phone property by setting the MoContactFieldPhones?

The problem is that if you fetch the contact phones from the Address Book and then you update the contact with no phones I need to delete the phones from the Address Book. 
If you don't fetch the phones then I won't touch the phones in the Address Book.

That NSLog won't be called because you just created the moContact without phones.
Your if should look like:

```
if(contact.phones && [contact.phones count] > 0){ //contact instead of moContact
       NSLog(@"phones availabes and should save");
}
```

**Comment by bb-git** [comment]
Thanks for the clarification. I'm now merging my own data with the data from the address book, so I don't lose any data no matter on which side the user changes it.
